Add UI
jmichalak9/msi pull request #8
Opened 2021-04-30 20:03 UTC by ozel981

I added UI to the project. Indirect calculations and calculation results are still not connected with the library.

2021-04-30 21:18 UTC, adassimo25 approved these changes

2021-05-01 10:51 UTC, jmichalak9 commented
przyciski są trochę za małe i ucina tekst

2021-05-01 10:52 UTC, jmichalak9 commented
W zakładce edit pogrupowałbym przyciski

2021-05-01 10:53 UTC, jmichalak9 commented
'Q' i 'R' zamieniłbym coś na bardzie czytelne dla użytkownika

2021-05-07 14:58 UTC, jmichalak9 requested changes

2021-05-07 14:58 UTC, jmichalak9 commented on msi/Examples/sadasdsa
> +{"Candidates":["dsafsdf","asdfsadfsa"],"JobPositions":["asdfasdf","sadfsadf","sadfsadfsa","sdgsdgsad"],"Skills":["asdfsadfsadf","gfdgdfb","dfhfdg"],"CandidatesRates":[[0,0,0],[0,0,0]],"JobPositionsRa
ten plik jest niepotrzebny

2021-05-07 14:58 UTC, jmichalak9 commented on msi/Set.cs
> +    class Set
```suggestion
    class InputSet
```

2021-05-07 15:01 UTC, jmichalak9 commented
Przy wpisaniu np. -5 pasowałoby zrobić walidację, ale nie musi być w tym PR

2021-05-07 18:44 UTC, jmichalak9 approved these changes

2021-05-09 15:17 UTC, merged